name: CI/CD Pipeline for Hexo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build Hexo site
      run: hexo generate

    - name: Build Docker image and push
      run: |
        docker build -t hexo-app .
        docker tag hexo-app <your-dockerhub-username>/hexo-app
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push <your-dockerhub-username>/hexo-app
